### ISSUE TITLE
Crashes with Django 1.11 (no BaseSettings anymore)

### ISSUE THREAD

**Issue by cuducos** [pyupio/pyup-django#2]
* pyup-django version: 0.3.0
* Django version: 1.11.1
* Python version: 3.6.1
* Operating System: macOS 10.12.4

### Description

`pyup-django` uses `django.conf.BaseSettings` which seems to removed in Django 1.11:

```
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/pyup_django/settings.py", line 2, in <module>
    from django.conf import BaseSettings, settings as django_settings
ImportError: cannot import name 'BaseSettings'

```

<details>
```
Traceback (most recent call last):
  File "/Users/cuducos/Sites/InternetSemLimites/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/pyup_django/admin.py", line 11, in <module>
    from .settings import settings
  File "/Users/cuducos/.virtualenvs/InternetSemLimites/lib/python3.6/site-packages/pyup_django/settings.py", line 2, in <module>
    from django.conf import BaseSettings, settings as django_settings
ImportError: cannot import name 'BaseSettings'
```
</details>

**Comment by cuducos** [comment]
[This](https://github.com/SmileyChris/django-countries/commit/13742dd8eed5b5675fb80fc6f0ff425bcf671e8b) could be helpful ; )

**Comment by jayfk** [comment]
> This could be helpful ; )

Thanks! :)
